//
//  RNRenderingConfig.h
//  Rayne
//
//  Copyright 2026 by Überpixel. All rights reserved.
//  Unauthorized use is punishable by torture, mutilation, and vivisection.
//

#ifndef __RAYNE_RENDERINGCONFIG_H_
#define __RAYNE_RENDERINGCONFIG_H_

#include "../Base/RNBase.h"

#ifndef RN_MODEL_LOD_DISABLED
	#define RN_MODEL_LOD_DISABLED 1
#endif

#ifndef RN_RENDERING_FRAME_STATISTICS_INTERVAL
	#define RN_RENDERING_FRAME_STATISTICS_INTERVAL 5.0f
#endif

#ifndef RN_RENDERING_FRAME_SUBMISSION_QUEUE_SIZE
	#define RN_RENDERING_FRAME_SUBMISSION_QUEUE_SIZE 1
#endif

#ifndef RN_RENDERING_ESTIMATED_DRAW_ITEMS_RESERVE_MULTIPLIER
	#define RN_RENDERING_ESTIMATED_DRAW_ITEMS_RESERVE_MULTIPLIER 2.0f
#endif

#ifndef RN_RENDERING_PREVIOUS_DRAW_ITEMS_RESERVE_MULTIPLIER
	#define RN_RENDERING_PREVIOUS_DRAW_ITEMS_RESERVE_MULTIPLIER 1.25f
#endif

#endif /* __RAYNE_RENDERINGCONFIG_H_ */
